<?php
    function location() {
        $labels = [
            'name'                  => _x('Locations', 'Post Type General Name', 'mightily'),
            'singular_name'         => _x('Location', 'Post Type Singular Name', 'mightily'),
            'menu_name'             => __('Locations', 'mightily'),
            'name_admin_bar'        => __('Locations', 'mightily'),
            'archives'              => __('Item Archives', 'mightily'),
            'attributes'            => __('Item Attributes', 'mightily'),
            'parent_item_colon'     => __('Parent Location:', 'mightily'),
            'all_items'             => __('All Locations', 'mightily'),
            'add_new_item'          => __('Add New Location', 'mightily'),
            'add_new'               => __('Add Location', 'mightily'),
            'new_item'              => __('New Location', 'mightily'),
            'edit_item'             => __('Edit Location', 'mightily'),
            'update_item'           => __('Update Location', 'mightily'),
            'view_item'             => __('View Location', 'mightily'),
            'view_items'            => __('View Locations', 'mightily'),
            'search_items'          => __('Search Locations', 'mightily'),
            'not_found'             => __('Not found', 'mightily'),
            'not_found_in_trash'    => __('Not found in Trash', 'mightily'),
            'featured_image'        => __('Featured Image', 'mightily'),
            'set_featured_image'    => __('Set featured image', 'mightily'),
            'remove_featured_image' => __('Remove featured image', 'mightily'),
            'use_featured_image'    => __('Use as featured image', 'mightily'),
            'insert_into_item'      => __('Insert into item', 'mightily'),
            'uploaded_to_this_item' => __('Uploaded to this item', 'mightily'),
            'items_list'            => __('Items list', 'mightily'),
            'items_list_navigation' => __('Items list navigation', 'mightily'),
            'filter_items_list'     => __('Filter items list', 'mightily'),
        ];
        $args = [
            'label'                 => __('Location', 'mightily'),
            'description'           => __('A collection of locations.', 'mightily'),
            'labels'                => $labels,
            'supports'              => [ 'title', 'editor', 'thumbnail' ],
            // 'taxonomies'            => [ 'location-types', 'difficulty', 'amenities', 'parks'  ],
            'hierarchical'          => false,
            'public'                => true,
            'show_ui'               => true,
            'show_in_menu'          => true,
            'menu_position'         => 20,
            'menu_icon'             => 'dashicons-admin-site',
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'can_export'            => true,
            'has_archive'           => false,
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'capability_type'       => 'page',
        ];
        register_post_type('location', $args);
    }
    add_action('init', 'location', 0);